from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

import cv2

from site_safety_vision.review import IncidentReviewEngine
from site_safety_vision.utils import ensure_dir, save_json, validate_file_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run second-level incident review using saved inference JSON."
    )

    parser.add_argument(
        "--json-path",
        type=str,
        required=True,
        help="Path to inference JSON file generated by run_inference.py",
    )
    parser.add_argument(
        "--video-path",
        type=str,
        default=None,
        help="Optional path to original video for screenshot extraction.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="outputs/reviews",
        help="Directory where review outputs will be saved.",
    )
    parser.add_argument(
        "--review-window-seconds",
        type=float,
        default=30.0,
        help="Minimum observation window for second-level review.",
    )
    parser.add_argument(
        "--minimum-ppe-verification-count",
        type=int,
        default=5,
        help="Minimum number of PPE verification events in the review window.",
    )
    parser.add_argument(
        "--minimum-unsafe-or-uncertain-ratio",
        type=float,
        default=0.5,
        help="Minimum unsafe/uncertain ratio for escalation.",
    )
    parser.add_argument(
        "--save-screenshots",
        action="store_true",
        help="Save representative screenshots for escalated cases.",
    )

    return parser.parse_args()


def load_json_file(json_path: Path) -> Dict[str, Any]:
    try:
        with json_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON file: {json_path}") from exc

    if not isinstance(data, dict):
        raise ValueError("JSON content must be a dictionary.")

    return data


def infer_video_name(json_path: Path, data: Dict[str, Any]) -> str:
    input_file = data.get("input_file")
    if input_file:
        return Path(str(input_file)).stem
    return json_path.stem.replace("_results", "")


def extract_fps(video_path: Path) -> float:
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        return 30.0

    try:
        fps = cap.get(cv2.CAP_PROP_FPS)
        if fps and fps > 0:
            return float(fps)
        return 30.0
    finally:
        cap.release()


def print_review_results(review_results: List[Dict[str, Any]]) -> None:
    if not review_results:
        print("No review results generated.")
        return

    for result in review_results:
        track_id = result["track_id"]
        status = result["review_status"]
        helmet_count = result["helmet_verification_count"]
        vest_count = result["vest_verification_count"]
        rep_frame = result["representative_frame_index"]

        print(f"Worker {track_id}: {status}")
        if status != "likely_compliant":
            print(f"  Representative frame: {rep_frame}")
            print(f"  Helmet verification count: {helmet_count}")
            print(f"  Vest verification count: {vest_count}")


def save_review_screenshots(
    video_path: Path,
    review_results: List[Dict[str, Any]],
    output_dir: Path,
) -> None:
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print(f"Could not open video for screenshot extraction: {video_path}")
        return

    try:
        escalated = [
            result
            for result in review_results
            if result["review_status"] in {"manual_review_required", "sustained_likely_violation"}
        ]

        for result in escalated:
            track_id = result["track_id"]
            frame_index = result["representative_frame_index"]

            cap.set(cv2.CAP_PROP_POS_FRAMES, frame_index)
            ok, frame = cap.read()

            if not ok or frame is None:
                print(f"Could not extract frame {frame_index} for worker {track_id}")
                continue

            output_path = output_dir / f"worker_{track_id}_frame_{frame_index}.jpg"
            cv2.imwrite(str(output_path), frame)
            print(f"Saved screenshot: {output_path}")

    finally:
        cap.release()


def main() -> None:
    args = parse_args()

    json_path = validate_file_path(args.json_path, must_exist=True)
    output_dir = ensure_dir(args.output_dir)

    data = load_json_file(json_path)

    video_path: Optional[Path] = None
    fps: Optional[float] = None
    if args.video_path:
        video_path = validate_file_path(args.video_path, must_exist=True)
        fps = extract_fps(video_path)

    review_engine = IncidentReviewEngine(
        review_window_seconds=args.review_window_seconds,
        minimum_ppe_verification_count=args.minimum_ppe_verification_count,
        minimum_unsafe_or_uncertain_ratio=args.minimum_unsafe_or_uncertain_ratio,
    )

    review_results = review_engine.review_video_results(data, fps=fps)

    print_review_results(review_results)

    video_name = infer_video_name(json_path, data)
    report_path = output_dir / f"{video_name}_review_report.json"

    save_json(
        {
            "source_json": str(json_path),
            "video_path": str(video_path) if video_path else None,
            "review_window_seconds": args.review_window_seconds,
            "minimum_ppe_verification_count": args.minimum_ppe_verification_count,
            "minimum_unsafe_or_uncertain_ratio": args.minimum_unsafe_or_uncertain_ratio,
            "review_results": review_results,
        },
        report_path,
    )
    print(f"Review report saved to: {report_path}")

    if args.save_screenshots:
        if video_path is None:
            print("Screenshots requested, but no --video-path was provided.")
        else:
            save_review_screenshots(video_path, review_results, output_dir)


if __name__ == "__main__":
    main()