from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict

from site_safety_vision.analytics import SiteSafetyAnalyticsEngine
from site_safety_vision.utils import ensure_dir, save_json, validate_file_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run site-level temporal safety analytics on saved inference JSON."
    )

    parser.add_argument(
        "--json-path",
        type=str,
        required=True,
        help="Path to inference JSON file generated by run_inference.py",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="outputs/analytics",
        help="Directory where analytics outputs will be saved.",
    )
    parser.add_argument(
        "--window-seconds",
        type=float,
        default=30.0,
        help="Window duration in seconds for windowed analytics.",
    )

    return parser.parse_args()


def load_json_file(json_path: Path) -> Dict[str, Any]:
    try:
        with json_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON file: {json_path}") from exc

    if not isinstance(data, dict):
        raise ValueError("JSON content must be a dictionary.")

    return data


def infer_base_name(json_path: Path, data: Dict[str, Any]) -> str:
    input_file = data.get("input_file")
    if input_file:
        return Path(str(input_file)).stem
    return json_path.stem.replace("_results", "")


def print_overall_summary(analytics_result: Dict[str, Any]) -> None:
    overall = analytics_result["overall"]

    print("Overall Site Safety Analytics")
    print(f"  Frames analyzed: {analytics_result['total_frames_processed']}")
    print(f"  Average persons detected per frame: {overall['average_persons_detected']:.2f}")
    print(f"  Average helmet-matched persons per frame: {overall['average_helmet_matched']:.2f}")
    print(f"  Average vest-matched persons per frame: {overall['average_vest_matched']:.2f}")
    print(f"  Average full-PPE persons per frame: {overall['average_full_ppe']:.2f}")
    print(f"  Average helmet-only persons per frame: {overall['average_helmet_only']:.2f}")
    print(f"  Average vest-only persons per frame: {overall['average_vest_only']:.2f}")
    print(
        f"  Average no-required-PPE-verified persons per frame: "
        f"{overall['average_no_required_ppe_verified']:.2f}"
    )
    print(f"  Helmet compliance rate: {overall['helmet_compliance_rate'] * 100:.1f}%")
    print(f"  Vest compliance rate: {overall['vest_compliance_rate'] * 100:.1f}%")
    print(f"  Full PPE compliance rate: {overall['full_ppe_compliance_rate'] * 100:.1f}%")


def main() -> None:
    args = parse_args()

    json_path = validate_file_path(args.json_path, must_exist=True)
    output_dir = ensure_dir(args.output_dir)

    data = load_json_file(json_path)

    engine = SiteSafetyAnalyticsEngine()
    analytics_result = engine.analyze_video_results(
        video_results=data,
        window_seconds=args.window_seconds,
    )

    print_overall_summary(analytics_result)

    base_name = infer_base_name(json_path, data)
    output_path = output_dir / f"{base_name}_analytics.json"

    save_json(
        {
            "source_json": str(json_path),
            "window_seconds": args.window_seconds,
            "analytics": analytics_result,
        },
        output_path,
    )

    print(f"Analytics report saved to: {output_path}")


if __name__ == "__main__":
    main()