from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Any, Dict, List, Optional, Tuple


@dataclass
class WorkerReviewResult:
    track_id: str
    review_status: str
    first_frame: int
    last_frame: int
    total_frames_seen: int
    safe_frames: int
    unsafe_frames: int
    uncertain_frames: int
    helmet_verification_count: int
    vest_verification_count: int
    representative_frame_index: int
    summary_message: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class IncidentReviewEngine:
    """
    Second-level review engine for analyzing worker behavior over time
    using the JSON output generated by the live inference pipeline.

    This version:
    - merges likely fragmented track IDs
    - is more forgiving when there is positive evidence of compliance
    - uses insufficient_observation for short / weak evidence cases
    """

    VALID_REVIEW_STATUSES = {
        "likely_compliant",
        "manual_review_required",
        "sustained_likely_violation",
        "insufficient_observation",
    }

    def __init__(
        self,
        review_window_seconds: float = 30.0,
        minimum_ppe_verification_count: int = 5,
        minimum_unsafe_or_uncertain_ratio: float = 0.5,
        max_merge_frame_gap: int = 30,
        max_merge_center_distance: float = 200.0,
    ) -> None:
        self.review_window_seconds = review_window_seconds
        self.minimum_ppe_verification_count = minimum_ppe_verification_count
        self.minimum_unsafe_or_uncertain_ratio = minimum_unsafe_or_uncertain_ratio
        self.max_merge_frame_gap = max_merge_frame_gap
        self.max_merge_center_distance = max_merge_center_distance

    def review_video_results(
        self,
        video_results: Dict[str, Any],
        fps: Optional[float] = None,
    ) -> List[Dict[str, Any]]:
        frames = video_results.get("frames", [])
        if not isinstance(frames, list):
            raise ValueError("Invalid video results: 'frames' must be a list.")

        worker_timelines = self._build_worker_timelines(frames)
        merged_timelines = self._merge_fragmented_tracks(worker_timelines)

        if fps is None or fps <= 0:
            fps = self._infer_fps(video_results)

        review_results: List[Dict[str, Any]] = []

        for merged_track_id, timeline in merged_timelines.items():
            result = self._review_worker(
                track_id=merged_track_id,
                timeline=timeline,
                fps=fps,
            )
            review_results.append(result.to_dict())

        review_results.sort(key=lambda item: item["first_frame"])
        return review_results

    def _build_worker_timelines(self, frames: List[Dict[str, Any]]) -> Dict[int, Dict[str, Any]]:
        worker_timelines: Dict[int, Dict[str, Any]] = {}

        for frame in frames:
            frame_index = int(frame.get("frame_index", 0))
            matched_results = frame.get("matched_results", [])
            worker_states = frame.get("worker_states", [])

            matched_by_track: Dict[int, Dict[str, Any]] = {}
            for match in matched_results:
                track_id = match.get("track_id")
                if track_id is None:
                    continue
                matched_by_track[int(track_id)] = match

            for worker_state in worker_states:
                track_id = worker_state.get("track_id")
                if track_id is None:
                    continue

                track_id = int(track_id)
                match = matched_by_track.get(track_id, {})
                person_bbox = match.get("person_bbox")

                if track_id not in worker_timelines:
                    worker_timelines[track_id] = {
                        "original_track_ids": [track_id],
                        "frame_indices": [],
                        "states": [],
                        "helmet_visible_frames": [],
                        "vest_visible_frames": [],
                        "unsafe_frame_indices": [],
                        "uncertain_frame_indices": [],
                        "safe_frame_indices": [],
                        "person_bboxes": [],
                        "frame_centers": [],
                    }

                timeline = worker_timelines[track_id]
                state = str(worker_state.get("state", "uncertain")).lower()

                timeline["frame_indices"].append(frame_index)
                timeline["states"].append(state)

                helmet_matched = match.get("helmet") is not None
                vest_matched = match.get("vest") is not None

                if helmet_matched:
                    timeline["helmet_visible_frames"].append(frame_index)
                if vest_matched:
                    timeline["vest_visible_frames"].append(frame_index)

                if state == "unsafe":
                    timeline["unsafe_frame_indices"].append(frame_index)
                elif state == "uncertain":
                    timeline["uncertain_frame_indices"].append(frame_index)
                elif state == "safe":
                    timeline["safe_frame_indices"].append(frame_index)

                if person_bbox is not None:
                    timeline["person_bboxes"].append(person_bbox)
                    timeline["frame_centers"].append((frame_index, self._bbox_center(person_bbox)))

        return worker_timelines

    def _merge_fragmented_tracks(
        self,
        worker_timelines: Dict[int, Dict[str, Any]],
    ) -> Dict[str, Dict[str, Any]]:
        track_items = []
        for track_id, timeline in worker_timelines.items():
            frame_indices = timeline["frame_indices"]
            if not frame_indices:
                continue

            start_frame = min(frame_indices)
            end_frame = max(frame_indices)
            start_center = self._get_center_near_frame(timeline, start_frame, prefer_start=True)
            end_center = self._get_center_near_frame(timeline, end_frame, prefer_start=False)

            track_items.append(
                {
                    "track_id": track_id,
                    "timeline": timeline,
                    "start_frame": start_frame,
                    "end_frame": end_frame,
                    "start_center": start_center,
                    "end_center": end_center,
                }
            )

        track_items.sort(key=lambda item: item["start_frame"])

        used = set()
        merged_timelines: Dict[str, Dict[str, Any]] = {}
        merged_index = 0

        for base in track_items:
            if base["track_id"] in used:
                continue

            group = [base]
            used.add(base["track_id"])

            changed = True
            while changed:
                changed = False
                last = group[-1]

                for candidate in track_items:
                    if candidate["track_id"] in used:
                        continue

                    if self._should_merge(last, candidate):
                        group.append(candidate)
                        used.add(candidate["track_id"])
                        changed = True
                        break

            merged_track_id = self._build_merged_track_id(group, merged_index)
            merged_timelines[merged_track_id] = self._combine_group_timelines(group)
            merged_index += 1

        return merged_timelines

    def _should_merge(self, a: Dict[str, Any], b: Dict[str, Any]) -> bool:
        frame_gap = b["start_frame"] - a["end_frame"]
        if frame_gap < 0 or frame_gap > self.max_merge_frame_gap:
            return False

        if a["end_center"] is None or b["start_center"] is None:
            return False

        distance = self._euclidean_distance(a["end_center"], b["start_center"])
        if distance > self.max_merge_center_distance:
            return False

        return True

    def _combine_group_timelines(self, group: List[Dict[str, Any]]) -> Dict[str, Any]:
        combined = {
            "original_track_ids": [],
            "frame_indices": [],
            "states": [],
            "helmet_visible_frames": [],
            "vest_visible_frames": [],
            "unsafe_frame_indices": [],
            "uncertain_frame_indices": [],
            "safe_frame_indices": [],
            "person_bboxes": [],
            "frame_centers": [],
        }

        for item in group:
            timeline = item["timeline"]
            combined["original_track_ids"].extend(timeline.get("original_track_ids", []))
            combined["frame_indices"].extend(timeline.get("frame_indices", []))
            combined["states"].extend(timeline.get("states", []))
            combined["helmet_visible_frames"].extend(timeline.get("helmet_visible_frames", []))
            combined["vest_visible_frames"].extend(timeline.get("vest_visible_frames", []))
            combined["unsafe_frame_indices"].extend(timeline.get("unsafe_frame_indices", []))
            combined["uncertain_frame_indices"].extend(timeline.get("uncertain_frame_indices", []))
            combined["safe_frame_indices"].extend(timeline.get("safe_frame_indices", []))
            combined["person_bboxes"].extend(timeline.get("person_bboxes", []))
            combined["frame_centers"].extend(timeline.get("frame_centers", []))

        combined["frame_indices"] = sorted(combined["frame_indices"])
        combined["helmet_visible_frames"] = sorted(combined["helmet_visible_frames"])
        combined["vest_visible_frames"] = sorted(combined["vest_visible_frames"])
        combined["unsafe_frame_indices"] = sorted(combined["unsafe_frame_indices"])
        combined["uncertain_frame_indices"] = sorted(combined["uncertain_frame_indices"])
        combined["safe_frame_indices"] = sorted(combined["safe_frame_indices"])
        combined["original_track_ids"] = sorted(set(combined["original_track_ids"]))
        combined["frame_centers"] = sorted(combined["frame_centers"], key=lambda x: x[0])

        return combined

    def _build_merged_track_id(self, group: List[Dict[str, Any]], merged_index: int) -> str:
        ids = [str(item["track_id"]) for item in group]
        if len(ids) == 1:
            return ids[0]
        return f"merged_{merged_index}_" + "_".join(ids)

    def _get_center_near_frame(
        self,
        timeline: Dict[str, Any],
        frame_index: int,
        prefer_start: bool,
    ) -> Optional[Tuple[float, float]]:
        centers = timeline.get("frame_centers", [])
        if not centers:
            return None

        if prefer_start:
            centers = sorted(centers, key=lambda x: x[0])
        else:
            centers = sorted(centers, key=lambda x: x[0], reverse=True)

        for fi, center in centers:
            if fi == frame_index:
                return center

        return centers[0][1] if centers else None

    def _infer_fps(self, video_results: Dict[str, Any]) -> float:
        total_frames = int(video_results.get("total_frames_processed", 0))
        if total_frames <= 0:
            return 1.0
        return 30.0

    def _review_worker(
        self,
        track_id: str,
        timeline: Dict[str, Any],
        fps: float,
    ) -> WorkerReviewResult:
        frame_indices: List[int] = timeline["frame_indices"]
        states: List[str] = timeline["states"]

        first_frame = min(frame_indices)
        last_frame = max(frame_indices)
        total_frames_seen = len(frame_indices)

        safe_frames = states.count("safe")
        unsafe_frames = states.count("unsafe")
        uncertain_frames = states.count("uncertain")

        helmet_verification_count = len(timeline["helmet_visible_frames"])
        vest_verification_count = len(timeline["vest_visible_frames"])

        visible_duration_seconds = total_frames_seen / fps if fps > 0 else float(total_frames_seen)
        unsafe_or_uncertain_frames = unsafe_frames + uncertain_frames
        unsafe_or_uncertain_ratio = (
            unsafe_or_uncertain_frames / total_frames_seen if total_frames_seen > 0 else 0.0
        )

        enough_window = visible_duration_seconds >= self.review_window_seconds
        low_helmet_verification = helmet_verification_count < self.minimum_ppe_verification_count
        low_vest_verification = vest_verification_count < self.minimum_ppe_verification_count
        high_problem_ratio = unsafe_or_uncertain_ratio >= self.minimum_unsafe_or_uncertain_ratio

        # Positive evidence shortcuts
        strong_positive_evidence = (
            safe_frames >= 20
            or helmet_verification_count >= 2
            or vest_verification_count >= 2
            or (helmet_verification_count >= 1 and vest_verification_count >= 1)
            or safe_frames > unsafe_frames
        )

        very_low_positive_evidence = (
            helmet_verification_count == 0
            and vest_verification_count == 0
            and safe_frames < 5
        )

        if strong_positive_evidence:
            review_status = "likely_compliant"
        elif not enough_window:
            if high_problem_ratio and very_low_positive_evidence and unsafe_frames > 10:
                review_status = "manual_review_required"
            else:
                review_status = "insufficient_observation"
        else:
            if (
                unsafe_frames > uncertain_frames
                and high_problem_ratio
                and low_helmet_verification
                and low_vest_verification
                and safe_frames < 10
            ):
                review_status = "sustained_likely_violation"
            elif high_problem_ratio and very_low_positive_evidence:
                review_status = "manual_review_required"
            elif high_problem_ratio and (low_helmet_verification or low_vest_verification) and safe_frames < 10:
                review_status = "manual_review_required"
            else:
                review_status = "likely_compliant"

        representative_frame_index = self._choose_representative_frame(timeline)

        summary_message = self._build_summary_message(
            track_id=track_id,
            review_status=review_status,
            visible_duration_seconds=visible_duration_seconds,
            helmet_verification_count=helmet_verification_count,
            vest_verification_count=vest_verification_count,
            unsafe_frames=unsafe_frames,
            uncertain_frames=uncertain_frames,
            safe_frames=safe_frames,
            original_track_ids=timeline.get("original_track_ids", []),
        )

        return WorkerReviewResult(
            track_id=track_id,
            review_status=review_status,
            first_frame=first_frame,
            last_frame=last_frame,
            total_frames_seen=total_frames_seen,
            safe_frames=safe_frames,
            unsafe_frames=unsafe_frames,
            uncertain_frames=uncertain_frames,
            helmet_verification_count=helmet_verification_count,
            vest_verification_count=vest_verification_count,
            representative_frame_index=representative_frame_index,
            summary_message=summary_message,
        )

    def _choose_representative_frame(self, timeline: Dict[str, Any]) -> int:
        unsafe_frames: List[int] = timeline["unsafe_frame_indices"]
        uncertain_frames: List[int] = timeline["uncertain_frame_indices"]
        frame_indices: List[int] = timeline["frame_indices"]

        if unsafe_frames:
            return unsafe_frames[0]
        if uncertain_frames:
            return uncertain_frames[0]
        if frame_indices:
            return frame_indices[len(frame_indices) // 2]
        return 0

    def _build_summary_message(
        self,
        track_id: str,
        review_status: str,
        visible_duration_seconds: float,
        helmet_verification_count: int,
        vest_verification_count: int,
        unsafe_frames: int,
        uncertain_frames: int,
        safe_frames: int,
        original_track_ids: List[int],
    ) -> str:
        merged_note = ""
        if len(original_track_ids) > 1:
            merged_note = f" Merged track IDs: {original_track_ids}."

        if review_status == "likely_compliant":
            return (
                f"Worker {track_id} is likely compliant. "
                f"Observed for {visible_duration_seconds:.1f}s. "
                f"Safe frames: {safe_frames}. "
                f"Helmet verified {helmet_verification_count} times, "
                f"vest verified {vest_verification_count} times."
                f"{merged_note}"
            )

        if review_status == "insufficient_observation":
            return (
                f"Worker {track_id} has insufficient observation for a firm review decision. "
                f"Observed for {visible_duration_seconds:.1f}s. "
                f"Safe frames: {safe_frames}, unsafe frames: {unsafe_frames}, uncertain frames: {uncertain_frames}."
                f"{merged_note}"
            )

        if review_status == "manual_review_required":
            return (
                f"Worker {track_id} requires manual review. "
                f"Observed for {visible_duration_seconds:.1f}s. "
                f"Safe frames: {safe_frames}. "
                f"Helmet verified {helmet_verification_count} times, "
                f"vest verified {vest_verification_count} times. "
                f"Unsafe frames: {unsafe_frames}, uncertain frames: {uncertain_frames}."
                f"{merged_note}"
            )

        return (
            f"Worker {track_id} shows a sustained likely violation. "
            f"Observed for {visible_duration_seconds:.1f}s. "
            f"Safe frames: {safe_frames}. "
            f"Helmet verified {helmet_verification_count} times, "
            f"vest verified {vest_verification_count} times. "
            f"Unsafe frames: {unsafe_frames}, uncertain frames: {uncertain_frames}."
            f"{merged_note}"
        )

    def _bbox_center(self, bbox: List[float] | Tuple[float, float, float, float]) -> Tuple[float, float]:
        x1, y1, x2, y2 = [float(v) for v in bbox]
        return ((x1 + x2) / 2.0, (y1 + y2) / 2.0)

    def _euclidean_distance(
        self,
        a: Tuple[float, float],
        b: Tuple[float, float],
    ) -> float:
        return ((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2) ** 0.5